<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>12.0</LangVersion>
    <RootNamespace>ATECore.TestFlowBuilder</RootNamespace>
    <AssemblyName>ATECore.TestFlowBuilder</AssemblyName>
    <ApplicationIcon>Assets\Icons\app.ico</ApplicationIcon>
    <Product>Test Flow Builder</Product>
    <Description>Test Flow Builder for ATECore</Description>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="Assets\Fonts\*.ttf" />
    <Resource Include="Assets\Icons\app.ico" />
  </ItemGroup>

</Project>
